lets filer data

In [4]:
import pandas as pd

comp= pd.read_csv(r"D:\sql_ultimate\sql-ultimate-course-main\datasets\Products.csv",encoding='utf-8')
comp

   ProductID Product     Category  Price
0        101  Bottle  Accessories     10
1        102    Tire  Accessories     15
2        103   Socks     Clothing     20
3        104    Caps     Clothing     25
4        105  Gloves     Clothing     30

In [8]:
# lets filter product and price
price_product=comp['Product']# this is serires data sturcture
# price_product

price_product= comp[['Product','Price']]# this is a data frame
price_product

  Product  Price
0  Bottle     10
1    Tire     15
2   Socks     20
3    Caps     25
4  Gloves     30