the problem is that find the high cell day and good rating day of super market

In [1]:
# important libs to use
import pandas as pd
import matplotlib.pyplot as pt
import datetime as dt
import seaborn as sb

In [2]:
# load data 
# data_f1=pd.read_csv(r"D:\data_analytic\reading pdf\archive (1)\annex1.csv")
data_f2 = pd.read_csv(r"D:\data_analytic\reading pdf\archive (1)\annex2.csv")

data_f3 = pd.read_csv(r"D:\data_analytic\reading pdf\archive (1)\annex3.csv")
# data_f4 = pd.read_csv(r"D:\data_analytic\reading pdf\archive (1)\annex4.csv",encoding='utf-8')

In [3]:
data_f2.info()

# data_f2.info()

<class 'pandas.DataFrame'>
RangeIndex: 878503 entries, 0 to 878502
Data columns (total 7 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   Date                         878503 non-null  str
 1   Time                         878503 non-null  str
 2   Item Code                    878503 non-null  int64
 3   Quantity Sold (kilo)         878503 non-null  float64
 4   Unit Selling Price (RMB/kg)  878503 non-null  float64
 5   Sale or Return               878503 non-null  str
 6   Discount (Yes/No)            878503 non-null  str
dtypes: float64(2), int64(1), str(4)
memory usage: 46.9 MB

In [4]:
data_f2.head(4)

,Date,Time,Item Code,Quantity Sold (kilo),Unit Selling Price (RMB/kg),Sale or Return,Discount (Yes/No)
0,2020-07-01,09:15:07.924,102900005117056,0.396,7.6,sale,No
1,2020-07-01,09:17:27.295,102900005115960,0.849,3.2,sale,No
2,2020-07-01,09:17:33.905,102900005117056,0.409,7.6,sale,No
3,2020-07-01,09:19:45.450,102900005115823,0.421,10.0,sale,No

In [5]:
# step 1 datetime tracking change the txt formet date time data into actual datetime type
data_f2['Date'] = pd.to_datetime(data_f2["Date"])

In [11]:
data_f2.info()

<class 'pandas.DataFrame'>
RangeIndex: 878503 entries, 0 to 878502
Data columns (total 7 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   Date                         878503 non-null  datetime64[us]
 1   Time                         878503 non-null  str
 2   Item Code                    878503 non-null  int64
 3   Quantity Sold (kilo)         878503 non-null  float64
 4   Unit Selling Price (RMB/kg)  878503 non-null  float64
 5   Sale or Return               878503 non-null  str
 6   Discount (Yes/No)            878503 non-null  str
dtypes: datetime64[us](1), float64(2), int64(1), str(3)
memory usage: 46.9 MB

In [32]:
# confirm it
# data_f2.info()
data_f2['Date'].head()

0   2020-07-01
1   2020-07-01
2   2020-07-01
3   2020-07-01
4   2020-07-01
Name: Date, dtype: datetime64[us]

In [ ]:
data_f2['Time'] = pd.to_datetime(data_f2["Time"])
# data_f2['Time'] = data_f2['Time'].dt.to_timestamp

In [16]:
# add a new column with days name
data_f2['Day_of_week']=  data_f2['Date'].dt.day_name() # type: ignore

In [13]:
data_f2.tail(4)

,Date,Time,Item Code,Quantity Sold (kilo),Unit Selling Price (RMB/kg),Sale or Return,Discount (Yes/No),Day_of_week
878499,2023-06-30,21:35:14.358,102900011022764,0.669,12.0,sale,No,Friday
878500,2023-06-30,21:35:20.264,102900005115250,0.125,24.0,sale,No,Friday
878501,2023-06-30,21:35:21.509,102900011016701,0.252,5.2,sale,No,Friday
878502,2023-06-30,21:40:48.248,102900011022764,0.803,12.0,sale,No,Friday

In [ ]:
df3_filt = data_f3[['Wholesale Price (RMB/kg)','Item Code']].drop_duplicates(subset='Item Code')
# extracting and merging
data_f2['Wholesale Price (RMB/kg)']= df3_filt['Wholesale Price (RMB/kg)']

In [36]:
data_f2.head(2)

,Date,Time,Item Code,Quantity Sold (kilo),Unit Selling Price (RMB/kg),Sale or Return,Discount (Yes/No),Day_of_week,Wholesale Price (RMB/kg)
0,2020-07-01,09:15:07.924,102900005117056,0.396,7.6,sale,No,Wednesday,3.88
1,2020-07-01,09:17:27.295,102900005115960,0.849,3.2,sale,No,Wednesday,6.72

In [37]:
data_f2.info()

<class 'pandas.DataFrame'>
RangeIndex: 878503 entries, 0 to 878502
Data columns (total 9 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   Date                         878503 non-null  datetime64[us]
 1   Time                         878503 non-null  str
 2   Item Code                    878503 non-null  int64
 3   Quantity Sold (kilo)         878503 non-null  float64
 4   Unit Selling Price (RMB/kg)  878503 non-null  float64
 5   Sale or Return               878503 non-null  str
 6   Discount (Yes/No)            878503 non-null  str
 7   Day_of_week                  878503 non-null  str
 8   Wholesale Price (RMB/kg)     251 non-null     float64
dtypes: datetime64[us](1), float64(3), int64(1), str(4)
memory usage: 60.3 MB

In [39]:
# aggregation find the average of total sale according to days
data_f2.groupby(['Day_of_week'])['Wholesale Price (RMB/kg)'].mean()

Day_of_week
Friday        7.030588
Monday        6.662692
Saturday     10.317895
Sunday        3.864483
Thursday     15.549048
Tuesday       6.385000
Wednesday     6.625882
Name: Wholesale Price (RMB/kg), dtype: float64

In [40]:
# find the sum of total cell by day
data_f2.groupby(['Day_of_week'])[['Wholesale Price (RMB/kg)']].sum()

             Wholesale Price (RMB/kg)
Day_of_week
Friday                         358.56
Monday                         173.23
Saturday                       392.08
Sunday                         112.07
Thursday                       326.53
Tuesday                        114.93
Wednesday                      450.56

In [ ]:
# graph with mt

In [ ]:
# graph with sb

In [45]:
data_f2['Item Code'] = data_f2['Item Code'].to_string
data_f2.info()

<class 'pandas.DataFrame'>
RangeIndex: 878503 entries, 0 to 878502
Data columns (total 9 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   Date                         878503 non-null  datetime64[us]
 1   Time                         878503 non-null  str
 2   Item Code                    878503 non-null  object
 3   Quantity Sold (kilo)         878503 non-null  float64
 4   Unit Selling Price (RMB/kg)  878503 non-null  float64
 5   Sale or Return               878503 non-null  str
 6   Discount (Yes/No)            878503 non-null  str
 7   Day_of_week                  878503 non-null  str
 8   Wholesale Price (RMB/kg)     251 non-null     float64
dtypes: datetime64[us](1), float64(3), object(1), str(4)
memory usage: 60.3+ MB

In [51]:
# now check the item which is mostly sold in everyday
data_f2.groupby(['Item Code'])[['Item Code','Day_of_week']].count()

                                                    Item Code  Day_of_week
Item Code
<bound method Series.to_string of 0         <bo...     878503       878503