In [1]:
import pandas as pd
import numpy as np

In [2]:
df= pd.read_csv(r'C:\Users\FatimaArain\Downloads\archive\retail_data\order_details.csv')

In [5]:
# check the data and find what can be done with thia data
df.head()

,OrderID,ProductID,Quantity,UnitCost,UnitPrice,DiscountRate,IsReturned,ReturnDate,ReturnTime,ReturnReason
0,ORD00001,PRDCT0056,3,2.14,3.38,0.00,0,9999-12-31,00:00:00,NaN
1,ORD00002,PRDCT0028,2,4.17,5.31,0.00,0,9999-12-31,00:00:00,NaN
2,ORD00002,PRDCT0001,13,20.36,25.77,0.05,0,9999-12-31,00:00:00,NaN
3,ORD00003,PRDCT0030,2,0.90,1.35,0.00,0,9999-12-31,00:00:00,NaN
4,ORD00004,PRDCT0003,3,12.84,20.35,0.00,0,9999-12-31,00:00:00,NaN

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 30271 entries, 0 to 30270
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   OrderID       30271 non-null  str
 1   ProductID     30271 non-null  str
 2   Quantity      30271 non-null  int64
 3   UnitCost      30271 non-null  float64
 4   UnitPrice     30271 non-null  float64
 5   DiscountRate  30271 non-null  float64
 6   IsReturned    30271 non-null  int64
 7   ReturnDate    30271 non-null  str
 8   ReturnTime    30271 non-null  str
 9   ReturnReason  1424 non-null   str
dtypes: float64(3), int64(2), str(5)
memory usage: 3.3 MB

In [4]:
# extract categorial data
df['IsReturned'].unique()
cat = df.loc[:,['IsReturned']]

In [5]:
# varify
cat.shape
cat.dtypes
cat['IsReturned'].dtype

dtype('int64')

In [6]:
type(cat['IsReturned'])

pandas.Series

In [7]:
# exttact productID,qunatity and unit price
a=['ProductID','Quantity','UnitPrice']
cat['ProductID']= df['ProductID']
cat['Quantity']= df['Quantity']
cat['UnitPrice']=df['UnitPrice']

In [8]:
cat

       IsReturned  ProductID  Quantity  UnitPrice
0               0  PRDCT0056         3       3.38
1               0  PRDCT0028         2       5.31
2               0  PRDCT0001        13      25.77
3               0  PRDCT0030         2       1.35
4               0  PRDCT0003         3      20.35
...           ...        ...       ...        ...
30266           0  PRDCT0049         2       5.44
30267           0  PRDCT0052         3       4.71
30268           0  PRDCT0033         3       4.06
30269           0  PRDCT0030         1       1.64
30270           0  PRDCT0018         1      11.66

[30271 rows x 4 columns]

In [9]:
# extraction
print(df.iloc[1])
print(df.iloc[5])
print(df.iloc[-1])

OrderID           ORD00002
ProductID        PRDCT0028
Quantity                 2
UnitCost              4.17
UnitPrice             5.31
DiscountRate           0.0
IsReturned               0
ReturnDate      9999-12-31
ReturnTime        00:00:00
ReturnReason           NaN
Name: 1, dtype: object
OrderID           ORD00004
ProductID        PRDCT0017
Quantity                 5
UnitCost              2.84
UnitPrice              3.6
DiscountRate           0.0
IsReturned               0
ReturnDate      9999-12-31
ReturnTime        00:00:00
ReturnReason           NaN
Name: 5, dtype: object
OrderID           ORD10000
ProductID        PRDCT0018
Quantity                 1
UnitCost              8.88
UnitPrice            11.66
DiscountRate          0.05
IsReturned               0
ReturnDate      9999-12-31
ReturnTime        00:00:00
ReturnReason           NaN
Name: 30270, dtype: object

In [10]:
# filter
avg = df['Quantity'].mean()
temp = df[df['Quantity'] > avg]

In [35]:
temp

,OrderID,ProductID,Quantity,UnitCost,UnitPrice,DiscountRate,IsReturned,ReturnDate,ReturnTime,ReturnReason
0,ORD00001,PRDCT0056,3,2.14,3.38,0.00,0,9999-12-31,00:00:00,NaN
2,ORD00002,PRDCT0001,13,20.36,25.77,0.05,0,9999-12-31,00:00:00,NaN
4,ORD00004,PRDCT0003,3,12.84,20.35,0.00,0,9999-12-31,00:00:00,NaN
5,ORD00004,PRDCT0017,5,2.84,3.60,0.00,0,9999-12-31,00:00:00,NaN
6,ORD00004,PRDCT0021,4,1.65,2.36,0.00,0,9999-12-31,00:00:00,NaN
...,...,...,...,...,...,...,...,...,...,...
30257,ORD09995,PRDCT0012,11,3.63,5.39,0.10,0,9999-12-31,00:00:00,NaN
30258,ORD09995,PRDCT0006,5,11.10,13.99,0.00,0,9999-12-31,00:00:00,NaN
30261,ORD09998,PRDCT0023,3,2.71,3.69,0.00,0,9999-12-31,00:00:00,NaN
30267,ORD09999,PRDCT0052,3,3.30,4.71,0.00,0,9999-12-31,00:00:00,NaN
30268,ORD09999,PRDCT0033,3,2.87,4.06,0.00,0,9999-12-31,00:00:00,NaN

In [16]:
avg

np.float64(2.681312146939315)

In [13]:
# use of and multi conditions 
return_rate=df['IsReturned'].mean()
# check the avg purchase qunatiy and avg is returned qunatiy greater then 
b = df[(df['IsReturned']> return_rate )& (df['Quantity']> avg)]

In [15]:
b.loc[:,['ProductID','IsReturned','Quantity']]

       ProductID  IsReturned  Quantity
35     PRDCT0029           1        18
61     PRDCT0016           1         3
88     PRDCT0001           1         4
89     PRDCT0027           1         3
140    PRDCT0025           1         8
...          ...         ...       ...
30091  PRDCT0069           1         4
30140  PRDCT0085           1         4
30166  PRDCT0028           1         3
30229  PRDCT0090           1         3
30242  PRDCT0062           1         4

[476 rows x 3 columns]

In [ ]:
# problem 7
# | 
# check the product id is quantity is greater then avg or is returner
re = df['Quantity'].mean()
r
df.loc[(df['Quantity'] > re) | (df['IsReturned']==1)]

,OrderID,ProductID,Quantity,UnitCost,UnitPrice,DiscountRate,IsReturned,ReturnDate,ReturnTime,ReturnReason
0,ORD00001,PRDCT0056,3,2.14,3.38,0.00,0,9999-12-31,00:00:00,NaN
2,ORD00002,PRDCT0001,13,20.36,25.77,0.05,0,9999-12-31,00:00:00,NaN
4,ORD00004,PRDCT0003,3,12.84,20.35,0.00,0,9999-12-31,00:00:00,NaN
5,ORD00004,PRDCT0017,5,2.84,3.60,0.00,0,9999-12-31,00:00:00,NaN
6,ORD00004,PRDCT0021,4,1.65,2.36,0.00,0,9999-12-31,00:00:00,NaN
...,...,...,...,...,...,...,...,...,...,...
30257,ORD09995,PRDCT0012,11,3.63,5.39,0.10,0,9999-12-31,00:00:00,NaN
30258,ORD09995,PRDCT0006,5,11.10,13.99,0.00,0,9999-12-31,00:00:00,NaN
30261,ORD09998,PRDCT0023,3,2.71,3.69,0.00,0,9999-12-31,00:00:00,NaN
30267,ORD09999,PRDCT0052,3,3.30,4.71,0.00,0,9999-12-31,00:00:00,NaN
30268,ORD09999,PRDCT0033,3,2.87,4.06,0.00,0,9999-12-31,00:00:00,NaN

In [6]:
# problem 9 extract categorical data
cati = [df['IsReturned'] == 0 ]

In [7]:
cati

[0        True
 1        True
 2        True
 3        True
 4        True
          ...
 30266    True
 30267    True
 30268    True
 30269    True
 30270    True
 Name: IsReturned, Length: 30271, dtype: bool]

In [8]:
# level 3
# make a new col profit 
df['Profit']= [True if i==1  else False  for i in df['IsReturned']]

In [12]:
df.columns

Index(['OrderID', 'ProductID', 'Quantity', 'UnitCost', 'UnitPrice',
       'DiscountRate', 'IsReturned', 'ReturnDate', 'ReturnTime',
       'ReturnReason', 'Profit', 'Net_Profit'],
      dtype='str')

In [11]:
df['Net_Profit'] = df['Quantity'] * (df['UnitPrice'] * (1 - df['DiscountRate']) - df['UnitCost'])

In [14]:
# find mising
df.isna().sum()

OrderID             0
ProductID           0
Quantity            0
UnitCost            0
UnitPrice           0
DiscountRate        0
IsReturned          0
ReturnDate          0
ReturnTime          0
ReturnReason    28847
Profit              0
Net_Profit          0
dtype: int64

In [7]:
# make a categorial col
# make a new column which describe the quantityt level low medium high
level=['Low','Medium','High']
avg = df['Quantity'].mean()
condition = [
    df['Quantity'] < avg,
   ( df['Quantity'] > avg )& (df['Quantity'] <=5),
   df['Quantity'] >5
]
df['Quantity_level'] = np.select(condition,level,default='Heighest')

In [8]:
df

,OrderID,ProductID,Quantity,UnitCost,UnitPrice,DiscountRate,IsReturned,ReturnDate,ReturnTime,ReturnReason,Quantity_level
0,ORD00001,PRDCT0056,3,2.14,3.38,0.00,0,9999-12-31,00:00:00,NaN,Medium
1,ORD00002,PRDCT0028,2,4.17,5.31,0.00,0,9999-12-31,00:00:00,NaN,Low
2,ORD00002,PRDCT0001,13,20.36,25.77,0.05,0,9999-12-31,00:00:00,NaN,High
3,ORD00003,PRDCT0030,2,0.90,1.35,0.00,0,9999-12-31,00:00:00,NaN,Low
4,ORD00004,PRDCT0003,3,12.84,20.35,0.00,0,9999-12-31,00:00:00,NaN,Medium
...,...,...,...,...,...,...,...,...,...,...,...
30266,ORD09999,PRDCT0049,2,3.73,5.44,0.00,0,9999-12-31,00:00:00,NaN,Low
30267,ORD09999,PRDCT0052,3,3.30,4.71,0.00,0,9999-12-31,00:00:00,NaN,Medium
30268,ORD09999,PRDCT0033,3,2.87,4.06,0.00,0,9999-12-31,00:00:00,NaN,Medium
30269,ORD10000,PRDCT0030,1,1.09,1.64,0.00,0,9999-12-31,00:00:00,NaN,Low
30270,ORD10000,PRDCT0018,1,8.88,11.66,0.05,0,9999-12-31,00:00:00,NaN,Low

In [9]:
# pro 11 
# find missing values
df.isna().sum()

OrderID               0
ProductID             0
Quantity              0
UnitCost              0
UnitPrice             0
DiscountRate          0
IsReturned            0
ReturnDate            0
ReturnTime            0
ReturnReason      28847
Quantity_level        0
dtype: int64

In [ ]:
# find percentage of missinng values
ob = df['ReturnReason'].isna().sum()

percentage =( ob/len(df)) * 100
percentage

np.float64(95.29582768986819)

In [16]:
# 95% data is missing it would be okay to drop this columns
df = df.drop(columns='ReturnReason')

In [17]:
df

,OrderID,ProductID,Quantity,UnitCost,UnitPrice,DiscountRate,IsReturned,ReturnDate,ReturnTime,Quantity_level
0,ORD00001,PRDCT0056,3,2.14,3.38,0.00,0,9999-12-31,00:00:00,Medium
1,ORD00002,PRDCT0028,2,4.17,5.31,0.00,0,9999-12-31,00:00:00,Low
2,ORD00002,PRDCT0001,13,20.36,25.77,0.05,0,9999-12-31,00:00:00,High
3,ORD00003,PRDCT0030,2,0.90,1.35,0.00,0,9999-12-31,00:00:00,Low
4,ORD00004,PRDCT0003,3,12.84,20.35,0.00,0,9999-12-31,00:00:00,Medium
...,...,...,...,...,...,...,...,...,...,...
30266,ORD09999,PRDCT0049,2,3.73,5.44,0.00,0,9999-12-31,00:00:00,Low
30267,ORD09999,PRDCT0052,3,3.30,4.71,0.00,0,9999-12-31,00:00:00,Medium
30268,ORD09999,PRDCT0033,3,2.87,4.06,0.00,0,9999-12-31,00:00:00,Medium
30269,ORD10000,PRDCT0030,1,1.09,1.64,0.00,0,9999-12-31,00:00:00,Low
30270,ORD10000,PRDCT0018,1,8.88,11.66,0.05,0,9999-12-31,00:00:00,Low

In [27]:
# pro 13 sort and highest
df.groupby(['ProductID'])['Quantity'].sum().sort_values(ascending=False).head(10)

ProductID
PRDCT0030    1415
PRDCT0014    1203
PRDCT0009    1176
PRDCT0025    1165
PRDCT0021    1129
PRDCT0020    1104
PRDCT0028    1099
PRDCT0026    1095
PRDCT0018    1094
PRDCT0005    1092
Name: Quantity, dtype: int64

In [28]:
# pro 14
# count frequncy
df['Quantity_level'].value_counts()

Quantity_level
Low       20438
Medium     8398
High       1435
Name: count, dtype: int64

In [30]:
# pro 15
# group by and aggregation
df.groupby(['ProductID'])['UnitPrice'].sum().sort_values(ascending=False).head(10)

ProductID
PRDCT0007    14403.86
PRDCT0005    13634.91
PRDCT0002    13584.97
PRDCT0010    10720.85
PRDCT0009     9976.71
PRDCT0001     9381.47
PRDCT0008     7245.01
PRDCT0003     6870.47
PRDCT0078     6122.44
PRDCT0071     6118.03
Name: UnitPrice, dtype: float64

In [34]:
# check the most product returned
df.groupby(['ProductID'])['IsReturned'].value_counts()

ProductID  IsReturned
PRDCT0001  0             362
           1              11
PRDCT0002  0             356
           1              12
PRDCT0003  0             369
                        ...
PRDCT0098  1               6
PRDCT0099  0             122
           1               4
PRDCT0100  0             138
           1               8
Name: count, Length: 200, dtype: int64

In [ ]:
# pro 17
# find the avrage of qunatity of each grop
df.groupby(['ProductID'])['Quantity'].mean(numeric_only=True).sort_values(ascending=False

ProductID
PRDCT0032    3.254902
PRDCT0030    3.215909
PRDCT0045    3.195122
PRDCT0031    2.982143
PRDCT0025    2.979540
               ...
PRDCT0049    2.368664
PRDCT0091    2.303704
PRDCT0095    2.286585
PRDCT0098    2.261538
PRDCT0099    2.126984
Name: Quantity, Length: 100, dtype: float64

In [42]:
# pro 17
# find the avrage of qunatity of each grop
df.groupby(['ProductID'])['Quantity'].std()

ProductID
PRDCT0001    3.640723
PRDCT0002    3.697993
PRDCT0003    2.864687
PRDCT0004    2.869171
PRDCT0005    3.222278
               ...
PRDCT0096    3.946919
PRDCT0097    3.716075
PRDCT0098    2.118775
PRDCT0099    1.696981
PRDCT0100    2.806599
Name: Quantity, Length: 100, dtype: float64

In [48]:
# pro 19 multi thinking
# calculate count on 2 cat col
df.groupby(['ProductID','Quantity_level'])['IsReturned'].value_counts()

ProductID  Quantity_level  IsReturned
PRDCT0001  High            0              23
           Low             0             240
                           1               3
           Medium          0              99
                           1               8
                                        ...
PRDCT0100  High            0               5
           Low             0              88
                           1               5
           Medium          0              45
                           1               3
Name: count, Length: 542, dtype: int64